# Generated by Django 2.0.6 on 2018-07-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardyloo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='essay',
            field=models.TextField(default='essay text'),
        ),
    ]
