# Generated by Django 2.0.6 on 2018-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardyloo', '0002_country_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(default='country image', upload_to='images/'),
        ),
    ]
