# Generated by Django 2.0.6 on 2018-07-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardyloo', '0004_auto_20180710_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='QCapital',
            field=models.TextField(default='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QCurrency',
            field=models.TextField(default='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QPoliticalLeader',
            field=models.TextField(default='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QSovereignty_Date',
            field=models.TextField(default='question'),
        ),
    ]
